# Generated by pyfloyd version 0.24.0.dev0
#    https://github.com/dpranke/pyfloyd
#
#    `flc -o src/pyfloyd/at_exp_parser.py grammars/at_exp.g`
#

import re
from typing import Any, Dict, NamedTuple, Optional

Externs = Optional[Dict[str, Any]]

# pylint: disable=too-many-lines


class _ParsingRuntimeError(Exception):
    pass


class Result(NamedTuple):
    """The result returned from a `parse()` call.

    If the parse is successful, `val` will contain the returned value, if
    any and `pos` will indicate the point in the text where the parser
    stopped.  If the parse is unsuccessful, `err` will contain a string
    describing any errors that occurred during the parse and `pos` will
    indicate the location of the farthest error in the text.
    """

    val: Any = None
    err: Optional[str] = None
    pos: Optional[int] = None


def parse(
    text: str, path: str = '<string>', externs: Externs = None, start: int = 0
) -> Result:
    """Parse a given text and return the result.

    If the parse was successful, `result.val` will be the returned value
    from the parse, and `result.pos` will indicate where the parser
    stopped when it was done parsing.

    If the parse is unsuccessful, `result.err` will be a string describing
    any errors found in the text, and `result.pos` will indicate the
    furthest point reached during the parse.

    If the optional `path` is provided it will be used in any error
    messages to indicate the path to the filename containing the given
    text.
    """
    return _Parser(text, path).parse(externs, start)


class _Parser:
    def __init__(self, text, path):
        self._text = text
        self._end = len(self._text)
        self._errpos = 0
        self._failed = False
        self._path = path
        self._pos = 0
        self._val = None
        self._externs = {
            'allow_trailing': False,
        }
        self._regexps = {}

    def parse(self, externs: Externs = None, start: int = 0):
        self._pos = start
        errors = ''
        if externs:
            for k, v in externs.items():
                if k in self._externs:
                    self._externs[k] = v
                else:
                    errors += f'Unexpected extern "{k}"\n'
        if errors:
            return Result(None, errors, 0)
        try:
            self._r_grammar()

            if self._failed:
                return Result(None, self._o_error(), self._errpos)
            return Result(self._val, None, self._pos)
        except _ParsingRuntimeError as e:  # pragma: no cover
            lineno, _ = self._o_offsets(self._errpos)
            return Result(
                None,
                self._path + ':' + str(lineno) + ' ' + str(e),
                self._errpos,
            )

    def _r_grammar(self):
        self._s_grammar_1()
        v__1 = self._val
        self._r_opt_end()
        if self._failed:
            return
        self._o_succeed(v__1, self._pos)

    def _s_grammar_1(self):
        vs = []
        while True:
            pos = self._pos
            self._r_term()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _r_term(self):
        pos = self._pos
        self._s_term_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_ch('\n')
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_term_2()

    def _s_term_1(self):
        self._o_ch('@')
        if self._failed:
            return
        self._r_at_expr()

    def _s_term_2(self):
        rexp = '[^@\n]+'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_opt_end(self):
        pos = self._pos
        v = self._externs['allow_trailing']
        if v is True:
            self._o_succeed(v, self._pos)
        elif v is False:
            self._o_fail()
        else:
            raise _ParsingRuntimeError('Bad predicate value')
        if not self._failed:
            return
        self._o_rewind(pos)
        self._r_end()

    def _r_ws(self):
        rexp = '[ \t\n]+'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_at_expr(self):
        pos = self._pos
        self._s_at_expr_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_at_expr_2()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_at_expr_3()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_at_expr_4()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_at_expr_5()

    def _s_at_expr_1(self):
        self._r_opt_id()
        v__1 = self._val
        self._r_list()
        if self._failed:
            return
        v__2 = self._val
        if self._failed:
            return
        self._r_braces()
        if self._failed:
            return
        v__3 = self._val
        if self._failed:
            return
        self._o_succeed(
            self._fn_concat(self._fn_cons(v__1, v__2), [v__3]), self._pos
        )

    def _s_at_expr_2(self):
        self._r_opt_id()
        v__1 = self._val
        self._r_list()
        if self._failed:
            return
        v__2 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_cons(v__1, v__2), self._pos)

    def _s_at_expr_3(self):
        self._r_opt_id()
        v__1 = self._val
        self._r_braces()
        if self._failed:
            return
        v__2 = self._val
        if self._failed:
            return
        self._o_succeed([v__1, v__2], self._pos)

    def _s_at_expr_4(self):
        self._r_id()
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(v__1, self._pos)

    def _s_at_expr_5(self):
        self._r_string()
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(v__1, self._pos)

    def _r_opt_id(self):
        pos = self._pos
        self._r_id()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_succeed(['symbol', 'lisp'], self._pos)

    def _r_id(self):
        self._s_id_1()
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(['symbol', v__1], self._pos)

    def _s_id_1(self):
        rexp = '[a-zA-Z_][\\.a-zA-Z0-9_]*'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_expr(self):
        pos = self._pos
        self._r_id()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_expr_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_expr_2()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._r_number()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._r_string()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._r_list()

    def _s_expr_1(self):
        self._o_str('true')
        if self._failed:
            return
        self._o_succeed(True, self._pos)

    def _s_expr_2(self):
        self._o_str('false')
        if self._failed:
            return
        self._o_succeed(False, self._pos)

    def _r_number(self):
        pos = self._pos
        self._s_number_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_number_2()

    def _s_number_1(self):
        self._o_ch('0')
        if self._failed:
            return
        self._o_succeed(0, self._pos)

    def _s_number_2(self):
        self._s_number_3()
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_atoi(v__1, 10), self._pos)

    def _s_number_3(self):
        rexp = '[1-9][0-9]*'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_string(self):
        pos = self._pos
        self._s_string_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_string_3()

    def _s_string_1(self):
        self._o_ch('"')
        if self._failed:
            return
        self._s_string_2()
        v__2 = self._val
        self._o_ch('"')
        if self._failed:
            return
        self._o_succeed(self._fn_join('', v__2), self._pos)

    def _s_string_2(self):
        vs = []
        while True:
            pos = self._pos
            self._r_dqch()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_string_3(self):
        self._o_ch("'")
        if self._failed:
            return
        self._s_string_4()
        v__2 = self._val
        self._o_ch("'")
        if self._failed:
            return
        self._o_succeed(self._fn_join('', v__2), self._pos)

    def _s_string_4(self):
        vs = []
        while True:
            pos = self._pos
            self._r_sqch()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _r_dqch(self):
        pos = self._pos
        self._s_dqch_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_dqch_2()

    def _s_dqch_1(self):
        self._o_str('\\"')
        if self._failed:
            return
        self._o_succeed('"', self._pos)

    def _s_dqch_2(self):
        rexp = '[^"]'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_sqch(self):
        pos = self._pos
        self._s_sqch_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_sqch_2()

    def _s_sqch_1(self):
        self._o_str("\\'")
        if self._failed:
            return
        self._o_succeed("'", self._pos)

    def _s_sqch_2(self):
        rexp = "[^']"
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_list(self):
        pos = self._pos
        self._s_list_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_list_6()

    def _s_list_1(self):
        self._o_ch('[')
        if self._failed:
            return
        self._s_list_2()
        self._r_expr()
        if self._failed:
            return
        v__3 = self._val
        if self._failed:
            return
        self._s_list_3()
        v__4 = self._val
        self._s_list_5()
        self._o_ch(']')
        if self._failed:
            return
        self._o_succeed(self._fn_cons(v__3, v__4), self._pos)

    def _s_list_2(self):
        self._r_ws()
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _s_list_3(self):
        vs = []
        while True:
            pos = self._pos
            self._s_list_4()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_list_4(self):
        self._r_ws()
        if self._failed:
            return
        self._r_expr()

    def _s_list_5(self):
        self._r_ws()
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _s_list_6(self):
        self._o_ch('[')
        if self._failed:
            return
        self._s_list_7()
        self._o_ch(']')
        if self._failed:
            return
        self._o_succeed([], self._pos)

    def _s_list_7(self):
        self._r_ws()
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _r_braces(self):
        self._o_ch('{')
        if self._failed:
            return
        self._s_braces_1()
        v__2 = self._val
        self._o_ch('}')
        if self._failed:
            return
        self._o_succeed(v__2, self._pos)

    def _s_braces_1(self):
        start = self._pos
        self._s_braces_2()
        end = self._pos
        self._val = self._text[start:end]

    def _s_braces_2(self):
        vs = []
        while True:
            pos = self._pos
            pos = self._pos
            errpos = self._errpos
            self._o_ch('}')
            if self._failed:
                self._o_succeed(None, pos)
            else:
                self._o_rewind(pos)
                self._errpos = errpos
                self._o_fail()
            if not self._failed:
                self._r_any()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _r_any(self):
        if self._pos < self._end:
            self._o_succeed(self._text[self._pos], self._pos + 1)
        else:
            self._o_fail()

    def _r_end(self):
        if self._pos == self._end:
            self._o_succeed(None, self._pos)
        else:
            self._o_fail()

    def _o_ch(self, ch):
        pos = self._pos
        if pos < self._end and self._text[pos] == ch:
            self._o_succeed(ch, self._pos + 1)
        else:
            self._o_fail()

    def _o_error(self):
        lineno, colno = self._o_offsets(self._errpos)
        if self._errpos == len(self._text):
            thing = 'end of input'
        else:
            thing = repr(self._text[self._errpos]).replace("'", '"')
        path = self._path
        return f'{path}:{lineno} Unexpected {thing} at column {colno}'

    def _o_fail(self):
        self._val = None
        self._failed = True
        self._errpos = max(self._errpos, self._pos)

    def _o_offsets(self, pos):
        lineno = 1
        colno = 1
        for i in range(pos):
            if self._text[i] == '\n':
                lineno += 1
                colno = 1
            else:
                colno += 1
        return lineno, colno

    def _o_rewind(self, newpos):
        self._o_succeed(None, newpos)

    def _o_str(self, s):
        for ch in s:
            self._o_ch(ch)
            if self._failed:
                return
        self._val = s

    def _o_succeed(self, v, newpos):
        self._val = v
        self._failed = False
        self._pos = newpos

    def _fn_atoi(self, s, base):
        return int(s, base)

    def _fn_concat(self, xs, ys):
        return xs + ys

    def _fn_cons(self, hd, tl):
        return [hd] + tl

    def _fn_join(self, sep, strs):
        return sep.join(strs)
