# Generated by pyfloyd version 0.24.0.dev0
#    https://github.com/dpranke/pyfloyd
#
#    `flc -o src/pyfloyd/datafile/parser.py grammars/datafile.g`
#

import re
from typing import Any, Dict, NamedTuple, Optional

Externs = Optional[Dict[str, Any]]

# pylint: disable=too-many-lines


class _ParsingRuntimeError(Exception):
    pass


class Result(NamedTuple):
    """The result returned from a `parse()` call.

    If the parse is successful, `val` will contain the returned value, if
    any and `pos` will indicate the point in the text where the parser
    stopped.  If the parse is unsuccessful, `err` will contain a string
    describing any errors that occurred during the parse and `pos` will
    indicate the location of the farthest error in the text.
    """

    val: Any = None
    err: Optional[str] = None
    pos: Optional[int] = None


def parse(
    text: str, path: str = '<string>', externs: Externs = None, start: int = 0
) -> Result:
    """Parse a given text and return the result.

    If the parse was successful, `result.val` will be the returned value
    from the parse, and `result.pos` will indicate where the parser
    stopped when it was done parsing.

    If the parse is unsuccessful, `result.err` will be a string describing
    any errors found in the text, and `result.pos` will indicate the
    furthest point reached during the parse.

    If the optional `path` is provided it will be used in any error
    messages to indicate the path to the filename containing the given
    text.
    """
    return _Parser(text, path).parse(externs, start)


class _Parser:
    def __init__(self, text, path):
        self._text = text
        self._end = len(self._text)
        self._errpos = 0
        self._failed = False
        self._path = path
        self._pos = 0
        self._val = None
        self._externs = {
            'memoize': True,
            'allow_trailing': False,
            'allow_numwords': False,
            'unicode': True,
            'unicode_names': True,
        }
        self._cache = {}
        self._regexps = {}
        self._scopes = []

    def parse(self, externs: Externs = None, start: int = 0):
        self._pos = start
        errors = ''
        if externs:
            for k, v in externs.items():
                if k in self._externs:
                    self._externs[k] = v
                else:
                    errors += f'Unexpected extern "{k}"\n'
        if errors:
            return Result(None, errors, 0)
        try:
            self._r_grammar()

            if self._failed:
                return Result(None, self._o_error(), self._errpos)
            return Result(self._val, None, self._pos)
        except _ParsingRuntimeError as e:  # pragma: no cover
            lineno, _ = self._o_offsets(self._errpos)
            return Result(
                None,
                self._path + ':' + str(lineno) + ' ' + str(e),
                self._errpos,
            )

    def _r_grammar(self):
        pos = self._pos
        self._s_grammar_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_grammar_3()

    def _s_grammar_1(self):
        self._s_grammar_2()
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_memoize('r__filler', self._r__filler)
        self._o_memoize('r_trailing', self._r_trailing)
        if self._failed:
            return
        self._o_succeed(['object', '', v__1], self._pos)

    def _s_grammar_2(self):
        vs = []
        self._o_memoize('r_member', self._r_member)
        if self._failed:
            return
        vs.append(self._val)
        while True:
            pos = self._pos
            self._o_memoize('r_member', self._r_member)
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_grammar_3(self):
        self._o_memoize('r_value', self._r_value)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_memoize('r__filler', self._r__filler)
        self._o_memoize('r_trailing', self._r_trailing)
        if self._failed:
            return
        self._o_succeed(v__1, self._pos)

    def _r_trailing(self):
        pos = self._pos
        self._s_trailing_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        v = self._externs['allow_trailing']
        if v is True:
            self._o_succeed(v, self._pos)
        elif v is False:
            self._o_fail()
        else:
            raise _ParsingRuntimeError('Bad predicate value')

    def _s_trailing_1(self):
        v = not self._externs['allow_trailing']
        if v is True:
            self._o_succeed(v, self._pos)
        elif v is False:
            self._o_fail()
        else:
            raise _ParsingRuntimeError('Bad predicate value')
        if self._failed:
            return
        self._o_memoize('r__filler', self._r__filler)
        self._o_memoize('r_end', self._r_end)

    def _r_eol(self):
        pos = self._pos
        self._o_str('\r\n')
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_ch('\r')
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_ch('\n')

    def _r_value(self):
        pos = self._pos
        self._s_value_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_value_2()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_value_3()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_value_4()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_value_5()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r_array', self._r_array)
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r_object', self._r_object)
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r_string', self._r_string)

    def _s_value_1(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_str('true')
        if self._failed:
            return
        self._o_succeed(['true', '', None], self._pos)

    def _s_value_2(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_str('false')
        if self._failed:
            return
        self._o_succeed(['false', '', None], self._pos)

    def _s_value_3(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_str('null')
        if self._failed:
            return
        self._o_succeed(['null', '', None], self._pos)

    def _s_value_4(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_memoize('r_numword', self._r_numword)

    def _s_value_5(self):
        self._s_value_6()
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(['number', '', v__1], self._pos)

    def _s_value_6(self):
        start = self._pos
        self._s_value_7()
        if self._failed:
            return
        end = self._pos
        self._val = self._text[start:end]

    def _s_value_7(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_memoize('r_number', self._r_number)

    def _r_number(self):
        pos = self._pos
        self._s_number_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_number_5()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_number_9()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_number_13()

    def _s_number_1(self):
        self._o_str('0b')
        if self._failed:
            return
        self._o_memoize('r_bin', self._r_bin)
        if self._failed:
            return
        self._s_number_2()

    def _s_number_2(self):
        vs = []
        while True:
            pos = self._pos
            self._s_number_3()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_number_3(self):
        pos = self._pos
        self._s_number_4()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r_bin', self._r_bin)

    def _s_number_4(self):
        self._o_ch('_')
        if self._failed:
            return
        self._o_memoize('r_bin', self._r_bin)

    def _s_number_5(self):
        self._o_str('0o')
        if self._failed:
            return
        self._o_memoize('r_oct', self._r_oct)
        if self._failed:
            return
        self._s_number_6()

    def _s_number_6(self):
        vs = []
        while True:
            pos = self._pos
            self._s_number_7()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_number_7(self):
        pos = self._pos
        self._s_number_8()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r_oct', self._r_oct)

    def _s_number_8(self):
        self._o_ch('_')
        if self._failed:
            return
        self._o_memoize('r_oct', self._r_oct)

    def _s_number_9(self):
        self._o_str('0x')
        if self._failed:
            return
        self._o_memoize('r_hex', self._r_hex)
        if self._failed:
            return
        self._s_number_10()

    def _s_number_10(self):
        vs = []
        while True:
            pos = self._pos
            self._s_number_11()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_number_11(self):
        pos = self._pos
        self._s_number_12()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r_hex', self._r_hex)

    def _s_number_12(self):
        self._o_ch('_')
        if self._failed:
            return
        self._o_memoize('r_hex', self._r_hex)

    def _s_number_13(self):
        self._s_number_14()
        self._o_memoize('r_int', self._r_int)
        if self._failed:
            return
        self._s_number_16()
        self._s_number_17()

    def _s_number_14(self):
        self._s_number_15()
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _s_number_15(self):
        pos = self._pos
        self._o_ch('-')
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_ch('+')

    def _s_number_16(self):
        self._o_memoize('r_frac', self._r_frac)
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _s_number_17(self):
        self._o_memoize('r_exp', self._r_exp)
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _r_int(self):
        pos = self._pos
        self._o_ch('0')
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_int_1()

    def _s_int_1(self):
        self._o_memoize('r_nonzerodigit', self._r_nonzerodigit)
        if self._failed:
            return
        self._o_memoize('r_digit_sep', self._r_digit_sep)

    def _r_digit_sep(self):
        vs = []
        while True:
            pos = self._pos
            self._s_digit_sep_1()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_digit_sep_1(self):
        pos = self._pos
        self._s_digit_sep_2()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r_digit', self._r_digit)

    def _s_digit_sep_2(self):
        self._o_ch('_')
        if self._failed:
            return
        self._o_memoize('r_digit', self._r_digit)

    def _r_digit(self):
        rexp = '[0-9]'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_nonzerodigit(self):
        rexp = '[1-9]'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_frac(self):
        self._o_ch('.')
        if self._failed:
            return
        self._s_frac_1()
        self._o_memoize('r_digit_sep', self._r_digit_sep)

    def _s_frac_1(self):
        self._o_memoize('r_digit', self._r_digit)
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _r_exp(self):
        self._s_exp_1()
        if self._failed:
            return
        self._s_exp_2()
        self._s_exp_4()
        self._o_memoize('r_digit_sep', self._r_digit_sep)

    def _s_exp_1(self):
        pos = self._pos
        self._o_ch('e')
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_ch('E')

    def _s_exp_2(self):
        self._s_exp_3()
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _s_exp_3(self):
        pos = self._pos
        self._o_ch('+')
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_ch('-')

    def _s_exp_4(self):
        self._o_memoize('r_digit', self._r_digit)
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _r_bin(self):
        rexp = '[01]'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_oct(self):
        rexp = '[0-7]'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_hex(self):
        rexp = '[0-9a-fA-F]'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_string(self):
        pos = self._pos
        self._s_string_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_string_3()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r_string_list', self._r_string_list)
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_string_5()

    def _s_string_1(self):
        self._o_memoize('r_raw_str_tag', self._r_raw_str_tag)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._s_string_2()
        if self._failed:
            return
        v__2 = self._val
        if self._failed:
            return
        self._o_succeed(['string', v__1, v__2], self._pos)

    def _s_string_2(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_memoize('r_raw_str', self._r_raw_str)

    def _s_string_3(self):
        self._o_memoize('r_string_tag', self._r_string_tag)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._s_string_4()
        if self._failed:
            return
        v__2 = self._val
        if self._failed:
            return
        self._o_succeed(['string', v__1, v__2], self._pos)

    def _s_string_4(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_memoize('r_str', self._r_str)

    def _s_string_5(self):
        self._s_string_6()
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(['bareword', '', v__1], self._pos)

    def _s_string_6(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_memoize('r_bareword', self._r_bareword)

    def _r_string_list(self):
        self._o_memoize('r_string_tag', self._r_string_tag)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch('(')
        if self._failed:
            return
        self._o_memoize('r_string', self._r_string)
        if self._failed:
            return
        v__3 = self._val
        if self._failed:
            return
        self._s_string_list_1()
        v__4 = self._val
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch(')')
        if self._failed:
            return
        self._o_succeed(
            ['string_list', v__1, self._fn_cons(v__3, v__4)], self._pos
        )

    def _s_string_list_1(self):
        vs = []
        while True:
            pos = self._pos
            self._s_string_list_2()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_string_list_2(self):
        self._s_string_list_3()
        self._o_memoize('r_string', self._r_string)

    def _s_string_list_3(self):
        self._s_string_list_4()
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _s_string_list_4(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch(',')

    def _r_raw_str_tag(self):
        self._s_raw_str_tag_1()
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._s_raw_str_tag_5()
        if self._failed:
            return
        self._o_succeed(v__1, self._pos)

    def _s_raw_str_tag_1(self):
        pos = self._pos
        self._s_raw_str_tag_2()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_raw_str_tag_3()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_raw_str_tag_4()

    def _s_raw_str_tag_2(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch('r')

    def _s_raw_str_tag_3(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_str('rd')

    def _s_raw_str_tag_4(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_str('dr')

    def _s_raw_str_tag_5(self):
        pos = self._pos
        errpos = self._errpos
        self._s_raw_str_tag_6()
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()

    def _s_raw_str_tag_6(self):
        pos = self._pos
        self._o_memoize('r__whitespace', self._r__whitespace)
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r__comment', self._r__comment)

    def _r_string_tag(self):
        self._s_string_tag_1()
        v__1 = self._val
        self._s_string_tag_3()
        if self._failed:
            return
        self._o_succeed(v__1, self._pos)

    def _s_string_tag_1(self):
        pos = self._pos
        self._s_string_tag_2()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r_tag', self._r_tag)

    def _s_string_tag_2(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch('d')

    def _s_string_tag_3(self):
        pos = self._pos
        errpos = self._errpos
        self._s_string_tag_4()
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()

    def _s_string_tag_4(self):
        pos = self._pos
        self._o_memoize('r__whitespace', self._r__whitespace)
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r__comment', self._r__comment)

    def _r_tag(self):
        pos = self._pos
        self._s_tag_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_tag_2()

    def _s_tag_1(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_memoize('r_bareword', self._r_bareword)

    def _s_tag_2(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_succeed('', self._pos)

    def _r_bareword(self):
        self._s_bareword_1()
        if self._failed:
            return
        self._s_bareword_3()

    def _s_bareword_1(self):
        pos = self._pos
        errpos = self._errpos
        self._s_bareword_2()
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()

    def _s_bareword_2(self):
        pos = self._pos
        self._o_str('true')
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_str('false')
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_str('null')
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r_number', self._r_number)

    def _s_bareword_3(self):
        start = self._pos
        self._s_bareword_4()
        if self._failed:
            return
        end = self._pos
        self._val = self._text[start:end]

    def _s_bareword_4(self):
        vs = []
        pos = self._pos
        errpos = self._errpos
        self._s_bareword_5()
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()
        if not self._failed:
            self._r_any()
        if self._failed:
            return
        vs.append(self._val)
        while True:
            pos = self._pos
            pos = self._pos
            errpos = self._errpos
            self._s_bareword_5()
            if self._failed:
                self._o_succeed(None, pos)
            else:
                self._o_rewind(pos)
                self._errpos = errpos
                self._o_fail()
            if not self._failed:
                self._r_any()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_bareword_5(self):
        pos = self._pos
        self._o_memoize('r_punct', self._r_punct)
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r__whitespace', self._r__whitespace)

    def _r_numword(self):
        self._s_numword_1()
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(['numword', '', v__1], self._pos)

    def _s_numword_1(self):
        start = self._pos
        self._s_numword_2()
        if self._failed:
            return
        end = self._pos
        self._val = self._text[start:end]

    def _s_numword_2(self):
        self._o_memoize('r_number', self._r_number)
        if self._failed:
            return
        self._s_numword_3()

    def _s_numword_3(self):
        vs = []
        pos = self._pos
        errpos = self._errpos
        self._s_numword_4()
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()
        if not self._failed:
            self._r_any()
        if self._failed:
            return
        vs.append(self._val)
        while True:
            pos = self._pos
            pos = self._pos
            errpos = self._errpos
            self._s_numword_4()
            if self._failed:
                self._o_succeed(None, pos)
            else:
                self._o_rewind(pos)
                self._errpos = errpos
                self._o_fail()
            if not self._failed:
                self._r_any()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_numword_4(self):
        pos = self._pos
        self._o_memoize('r_punct', self._r_punct)
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r__whitespace', self._r__whitespace)

    def _r_raw_str(self):
        pos = self._pos
        self._scopes.append({})
        self._s_raw_str_1()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_raw_str_4()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_raw_str_7()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_raw_str_10()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_raw_str_13()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_raw_str_16()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_raw_str_19()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_raw_str_25()
        self._scopes.pop()

    def _s_raw_str_1(self):
        self._o_memoize('r_tsq', self._r_tsq)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v__2 = self._val
        self._s_raw_str_2()
        v__3 = self._val
        self._o_memoize('r_tsq', self._r_tsq)
        if self._failed:
            return
        self._o_succeed([v__1, v__2, v__3], self._pos)

    def _s_raw_str_2(self):
        start = self._pos
        self._s_raw_str_3()
        end = self._pos
        self._val = self._text[start:end]

    def _s_raw_str_3(self):
        vs = []
        while True:
            pos = self._pos
            pos = self._pos
            errpos = self._errpos
            self._o_memoize('r_tsq', self._r_tsq)
            if self._failed:
                self._o_succeed(None, pos)
            else:
                self._o_rewind(pos)
                self._errpos = errpos
                self._o_fail()
            if not self._failed:
                self._r_any()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_raw_str_4(self):
        self._o_memoize('r_tdq', self._r_tdq)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v__2 = self._val
        self._s_raw_str_5()
        v__3 = self._val
        self._o_memoize('r_tdq', self._r_tdq)
        if self._failed:
            return
        self._o_succeed([v__1, v__2, v__3], self._pos)

    def _s_raw_str_5(self):
        start = self._pos
        self._s_raw_str_6()
        end = self._pos
        self._val = self._text[start:end]

    def _s_raw_str_6(self):
        vs = []
        while True:
            pos = self._pos
            pos = self._pos
            errpos = self._errpos
            self._o_memoize('r_tdq', self._r_tdq)
            if self._failed:
                self._o_succeed(None, pos)
            else:
                self._o_rewind(pos)
                self._errpos = errpos
                self._o_fail()
            if not self._failed:
                self._r_any()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_raw_str_7(self):
        self._o_memoize('r_tbq', self._r_tbq)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v__2 = self._val
        self._s_raw_str_8()
        v__3 = self._val
        self._o_memoize('r_tbq', self._r_tbq)
        if self._failed:
            return
        self._o_succeed([v__1, v__2, v__3], self._pos)

    def _s_raw_str_8(self):
        start = self._pos
        self._s_raw_str_9()
        end = self._pos
        self._val = self._text[start:end]

    def _s_raw_str_9(self):
        vs = []
        while True:
            pos = self._pos
            pos = self._pos
            errpos = self._errpos
            self._o_memoize('r_tbq', self._r_tbq)
            if self._failed:
                self._o_succeed(None, pos)
            else:
                self._o_rewind(pos)
                self._errpos = errpos
                self._o_fail()
            if not self._failed:
                self._r_any()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_raw_str_10(self):
        self._o_memoize('r_sq', self._r_sq)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v__2 = self._val
        self._s_raw_str_11()
        v__3 = self._val
        self._o_memoize('r_sq', self._r_sq)
        if self._failed:
            return
        self._o_succeed([v__1, v__2, v__3], self._pos)

    def _s_raw_str_11(self):
        start = self._pos
        self._s_raw_str_12()
        end = self._pos
        self._val = self._text[start:end]

    def _s_raw_str_12(self):
        vs = []
        while True:
            pos = self._pos
            pos = self._pos
            errpos = self._errpos
            self._o_memoize('r_sq', self._r_sq)
            if self._failed:
                self._o_succeed(None, pos)
            else:
                self._o_rewind(pos)
                self._errpos = errpos
                self._o_fail()
            if not self._failed:
                self._r_any()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_raw_str_13(self):
        self._o_memoize('r_dq', self._r_dq)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v__2 = self._val
        self._s_raw_str_14()
        v__3 = self._val
        self._o_memoize('r_dq', self._r_dq)
        if self._failed:
            return
        self._o_succeed([v__1, v__2, v__3], self._pos)

    def _s_raw_str_14(self):
        start = self._pos
        self._s_raw_str_15()
        end = self._pos
        self._val = self._text[start:end]

    def _s_raw_str_15(self):
        vs = []
        while True:
            pos = self._pos
            pos = self._pos
            errpos = self._errpos
            self._o_memoize('r_dq', self._r_dq)
            if self._failed:
                self._o_succeed(None, pos)
            else:
                self._o_rewind(pos)
                self._errpos = errpos
                self._o_fail()
            if not self._failed:
                self._r_any()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_raw_str_16(self):
        self._o_memoize('r_bq', self._r_bq)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v__2 = self._val
        self._s_raw_str_17()
        v__3 = self._val
        self._o_memoize('r_bq', self._r_bq)
        if self._failed:
            return
        self._o_succeed([v__1, v__2, v__3], self._pos)

    def _s_raw_str_17(self):
        start = self._pos
        self._s_raw_str_18()
        end = self._pos
        self._val = self._text[start:end]

    def _s_raw_str_18(self):
        vs = []
        while True:
            pos = self._pos
            pos = self._pos
            errpos = self._errpos
            self._o_memoize('r_bq', self._r_bq)
            if self._failed:
                self._o_succeed(None, pos)
            else:
                self._o_rewind(pos)
                self._errpos = errpos
                self._o_fail()
            if not self._failed:
                self._r_any()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_raw_str_19(self):
        self._o_ch('L')
        if self._failed:
            return
        self._s_raw_str_20()
        if self._failed:
            return
        self._scopes[-1]['lq'] = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v_c = self._val
        self._s_raw_str_23()
        v_s = self._val
        self._o_str(self._o_lookup('lq'))
        if self._failed:
            return
        self._o_succeed(
            [self._fn_strcat('L', self._o_lookup('lq')), v_c, v_s], self._pos
        )

    def _s_raw_str_20(self):
        start = self._pos
        self._s_raw_str_21()
        if self._failed:
            return
        end = self._pos
        self._val = self._text[start:end]

    def _s_raw_str_21(self):
        self._o_memoize('r_sq', self._r_sq)
        if self._failed:
            return
        self._s_raw_str_22()
        if self._failed:
            return
        self._o_memoize('r_sq', self._r_sq)

    def _s_raw_str_22(self):
        vs = []
        self._o_ch('=')
        if self._failed:
            return
        vs.append(self._val)
        while True:
            pos = self._pos
            self._o_ch('=')
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_raw_str_23(self):
        start = self._pos
        self._s_raw_str_24()
        end = self._pos
        self._val = self._text[start:end]

    def _s_raw_str_24(self):
        vs = []
        while True:
            pos = self._pos
            pos = self._pos
            errpos = self._errpos
            self._o_str(self._o_lookup('lq'))
            if self._failed:
                self._o_succeed(None, pos)
            else:
                self._o_rewind(pos)
                self._errpos = errpos
                self._o_fail()
            if not self._failed:
                self._r_any()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_raw_str_25(self):
        self._o_ch('[')
        if self._failed:
            return
        self._s_raw_str_26()
        if self._failed:
            return
        self._scopes[-1]['eqs'] = self._val
        if self._failed:
            return
        self._o_ch('[')
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v_c = self._val
        self._s_raw_str_27()
        v_s = self._val
        self._o_ch(']')
        if self._failed:
            return
        self._o_str(self._o_lookup('eqs'))
        if self._failed:
            return
        self._o_ch(']')
        if self._failed:
            return
        self._o_succeed(
            [
                self._fn_strcat(
                    '[',
                    self._fn_strcat(
                        self._fn_join('', self._o_lookup('eqs')), ']'
                    ),
                ),
                v_c,
                v_s,
            ],
            self._pos,
        )

    def _s_raw_str_26(self):
        vs = []
        self._o_ch('=')
        if self._failed:
            return
        vs.append(self._val)
        while True:
            pos = self._pos
            self._o_ch('=')
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_raw_str_27(self):
        start = self._pos
        self._s_raw_str_28()
        end = self._pos
        self._val = self._text[start:end]

    def _s_raw_str_28(self):
        vs = []
        while True:
            pos = self._pos
            pos = self._pos
            errpos = self._errpos
            self._s_raw_str_29()
            if self._failed:
                self._o_succeed(None, pos)
            else:
                self._o_rewind(pos)
                self._errpos = errpos
                self._o_fail()
            if not self._failed:
                self._r_any()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_raw_str_29(self):
        self._o_ch(']')
        if self._failed:
            return
        self._o_str(self._o_lookup('eqs'))
        if self._failed:
            return
        self._o_ch(']')

    def _r_str(self):
        pos = self._pos
        self._scopes.append({})
        self._s_str_1()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_str_6()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_str_11()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_str_16()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_str_21()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_str_26()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_str_31()
        self._scopes.pop()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._scopes.append({})
        self._s_str_39()
        self._scopes.pop()

    def _s_str_1(self):
        self._o_memoize('r_tsq', self._r_tsq)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v__2 = self._val
        self._s_str_2()
        v__3 = self._val
        self._o_memoize('r_tsq', self._r_tsq)
        if self._failed:
            return
        self._o_succeed([v__1, v__2, v__3], self._pos)

    def _s_str_2(self):
        start = self._pos
        self._s_str_3()
        end = self._pos
        self._val = self._text[start:end]

    def _s_str_3(self):
        vs = []
        while True:
            pos = self._pos
            self._s_str_4()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_str_4(self):
        self._s_str_5()
        if self._failed:
            return
        self._o_memoize('r_bchar', self._r_bchar)

    def _s_str_5(self):
        pos = self._pos
        errpos = self._errpos
        self._o_memoize('r_tsq', self._r_tsq)
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()

    def _s_str_6(self):
        self._o_memoize('r_tdq', self._r_tdq)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v__2 = self._val
        self._s_str_7()
        v__3 = self._val
        self._o_memoize('r_tdq', self._r_tdq)
        if self._failed:
            return
        self._o_succeed([v__1, v__2, v__3], self._pos)

    def _s_str_7(self):
        start = self._pos
        self._s_str_8()
        end = self._pos
        self._val = self._text[start:end]

    def _s_str_8(self):
        vs = []
        while True:
            pos = self._pos
            self._s_str_9()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_str_9(self):
        self._s_str_10()
        if self._failed:
            return
        self._o_memoize('r_bchar', self._r_bchar)

    def _s_str_10(self):
        pos = self._pos
        errpos = self._errpos
        self._o_memoize('r_tdq', self._r_tdq)
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()

    def _s_str_11(self):
        self._o_memoize('r_tbq', self._r_tbq)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v__2 = self._val
        self._s_str_12()
        v__3 = self._val
        self._o_memoize('r_tbq', self._r_tbq)
        if self._failed:
            return
        self._o_succeed([v__1, v__2, v__3], self._pos)

    def _s_str_12(self):
        start = self._pos
        self._s_str_13()
        end = self._pos
        self._val = self._text[start:end]

    def _s_str_13(self):
        vs = []
        while True:
            pos = self._pos
            self._s_str_14()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_str_14(self):
        self._s_str_15()
        if self._failed:
            return
        self._o_memoize('r_bchar', self._r_bchar)

    def _s_str_15(self):
        pos = self._pos
        errpos = self._errpos
        self._o_memoize('r_tbq', self._r_tbq)
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()

    def _s_str_16(self):
        self._o_memoize('r_sq', self._r_sq)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v__2 = self._val
        self._s_str_17()
        v__3 = self._val
        self._o_memoize('r_sq', self._r_sq)
        if self._failed:
            return
        self._o_succeed([v__1, v__2, v__3], self._pos)

    def _s_str_17(self):
        start = self._pos
        self._s_str_18()
        end = self._pos
        self._val = self._text[start:end]

    def _s_str_18(self):
        vs = []
        while True:
            pos = self._pos
            self._s_str_19()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_str_19(self):
        self._s_str_20()
        if self._failed:
            return
        self._o_memoize('r_bchar', self._r_bchar)

    def _s_str_20(self):
        pos = self._pos
        errpos = self._errpos
        self._o_memoize('r_sq', self._r_sq)
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()

    def _s_str_21(self):
        self._o_memoize('r_dq', self._r_dq)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v__2 = self._val
        self._s_str_22()
        v__3 = self._val
        self._o_memoize('r_dq', self._r_dq)
        if self._failed:
            return
        self._o_succeed([v__1, v__2, v__3], self._pos)

    def _s_str_22(self):
        start = self._pos
        self._s_str_23()
        end = self._pos
        self._val = self._text[start:end]

    def _s_str_23(self):
        vs = []
        while True:
            pos = self._pos
            self._s_str_24()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_str_24(self):
        self._s_str_25()
        if self._failed:
            return
        self._o_memoize('r_bchar', self._r_bchar)

    def _s_str_25(self):
        pos = self._pos
        errpos = self._errpos
        self._o_memoize('r_dq', self._r_dq)
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()

    def _s_str_26(self):
        self._o_memoize('r_bq', self._r_bq)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v__2 = self._val
        self._s_str_27()
        v__3 = self._val
        self._o_memoize('r_bq', self._r_bq)
        if self._failed:
            return
        self._o_succeed([v__1, v__2, v__3], self._pos)

    def _s_str_27(self):
        start = self._pos
        self._s_str_28()
        end = self._pos
        self._val = self._text[start:end]

    def _s_str_28(self):
        vs = []
        while True:
            pos = self._pos
            self._s_str_29()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_str_29(self):
        self._s_str_30()
        if self._failed:
            return
        self._o_memoize('r_bchar', self._r_bchar)

    def _s_str_30(self):
        pos = self._pos
        errpos = self._errpos
        self._o_memoize('r_bq', self._r_bq)
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()

    def _s_str_31(self):
        self._o_ch('L')
        if self._failed:
            return
        self._s_str_32()
        if self._failed:
            return
        self._scopes[-1]['lq'] = self._val
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v_c = self._val
        self._s_str_35()
        v_s = self._val
        self._o_str(self._o_lookup('lq'))
        if self._failed:
            return
        self._o_succeed(
            [self._fn_strcat('L', self._o_lookup('lq')), v_c, v_s], self._pos
        )

    def _s_str_32(self):
        start = self._pos
        self._s_str_33()
        if self._failed:
            return
        end = self._pos
        self._val = self._text[start:end]

    def _s_str_33(self):
        self._o_memoize('r_sq', self._r_sq)
        if self._failed:
            return
        self._s_str_34()
        if self._failed:
            return
        self._o_memoize('r_sq', self._r_sq)

    def _s_str_34(self):
        vs = []
        self._o_ch('=')
        if self._failed:
            return
        vs.append(self._val)
        while True:
            pos = self._pos
            self._o_ch('=')
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_str_35(self):
        start = self._pos
        self._s_str_36()
        end = self._pos
        self._val = self._text[start:end]

    def _s_str_36(self):
        vs = []
        while True:
            pos = self._pos
            self._s_str_37()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_str_37(self):
        self._s_str_38()
        if self._failed:
            return
        self._o_memoize('r_bchar', self._r_bchar)

    def _s_str_38(self):
        pos = self._pos
        errpos = self._errpos
        self._o_str(self._o_lookup('lq'))
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()

    def _s_str_39(self):
        self._o_ch('[')
        if self._failed:
            return
        self._s_str_40()
        if self._failed:
            return
        self._scopes[-1]['eqs'] = self._val
        if self._failed:
            return
        self._o_ch('[')
        if self._failed:
            return
        self._o_succeed(self._fn_colno(), self._pos)
        v_c = self._val
        self._s_str_41()
        v_s = self._val
        self._o_ch(']')
        if self._failed:
            return
        self._o_str(self._o_lookup('eqs'))
        if self._failed:
            return
        self._o_ch(']')
        if self._failed:
            return
        self._o_succeed(
            [
                self._fn_strcat(
                    '[',
                    self._fn_strcat(
                        self._fn_join('', self._o_lookup('eqs')), ']'
                    ),
                ),
                v_c,
                v_s,
            ],
            self._pos,
        )

    def _s_str_40(self):
        vs = []
        self._o_ch('=')
        if self._failed:
            return
        vs.append(self._val)
        while True:
            pos = self._pos
            self._o_ch('=')
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_str_41(self):
        start = self._pos
        self._s_str_42()
        end = self._pos
        self._val = self._text[start:end]

    def _s_str_42(self):
        vs = []
        while True:
            pos = self._pos
            self._s_str_43()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_str_43(self):
        self._s_str_44()
        if self._failed:
            return
        self._o_memoize('r_bchar', self._r_bchar)

    def _s_str_44(self):
        pos = self._pos
        errpos = self._errpos
        self._s_str_45()
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()

    def _s_str_45(self):
        self._o_ch(']')
        if self._failed:
            return
        self._o_str(self._o_lookup('eqs'))
        if self._failed:
            return
        self._o_ch(']')

    def _r_punct(self):
        rexp = "(L'=+')|[/#'\"`\\[\\](){}:=,]"
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_sq(self):
        self._o_ch("'")

    def _r_dq(self):
        self._o_ch('"')

    def _r_bq(self):
        self._o_ch('`')

    def _r_tsq(self):
        self._o_str("'''")

    def _r_tbq(self):
        self._o_str('```')

    def _r_tdq(self):
        self._o_str('"""')

    def _r_bchar(self):
        pos = self._pos
        self._s_bchar_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r_any', self._r_any)

    def _s_bchar_1(self):
        self._o_memoize('r_bslash', self._r_bslash)
        if self._failed:
            return
        self._o_memoize('r_escape', self._r_escape)

    def _r_bslash(self):
        self._o_ch('\\')

    def _r_escape(self):
        pos = self._pos
        self._o_memoize('r_bslash', self._r_bslash)
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_escape_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_escape_2()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_escape_3()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_escape_5()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_escape_7()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_escape_9()

    def _s_escape_1(self):
        rexp = '[abfnrtv\'"`]'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _s_escape_2(self):
        vs = []
        i = 0
        cmin = 1
        cmax = 3
        while i < cmax:
            self._o_memoize('r_oct', self._r_oct)
            if self._failed:
                if i >= cmin:
                    self._o_succeed(vs, self._pos)
                return
            vs.append(self._val)
            i += 1
        self._o_succeed(vs, self._pos)

    def _s_escape_3(self):
        self._o_ch('x')
        if self._failed:
            return
        self._s_escape_4()

    def _s_escape_4(self):
        vs = []
        i = 0
        cmin = 2
        cmax = 2
        while i < cmax:
            self._o_memoize('r_hex', self._r_hex)
            if self._failed:
                if i >= cmin:
                    self._o_succeed(vs, self._pos)
                return
            vs.append(self._val)
            i += 1
        self._o_succeed(vs, self._pos)

    def _s_escape_5(self):
        v = self._externs['unicode']
        if v is True:
            self._o_succeed(v, self._pos)
        elif v is False:
            self._o_fail()
        else:
            raise _ParsingRuntimeError('Bad predicate value')
        if self._failed:
            return
        self._o_ch('u')
        if self._failed:
            return
        self._s_escape_6()

    def _s_escape_6(self):
        vs = []
        i = 0
        cmin = 4
        cmax = 4
        while i < cmax:
            self._o_memoize('r_hex', self._r_hex)
            if self._failed:
                if i >= cmin:
                    self._o_succeed(vs, self._pos)
                return
            vs.append(self._val)
            i += 1
        self._o_succeed(vs, self._pos)

    def _s_escape_7(self):
        v = self._externs['unicode']
        if v is True:
            self._o_succeed(v, self._pos)
        elif v is False:
            self._o_fail()
        else:
            raise _ParsingRuntimeError('Bad predicate value')
        if self._failed:
            return
        self._o_ch('U')
        if self._failed:
            return
        self._s_escape_8()

    def _s_escape_8(self):
        vs = []
        i = 0
        cmin = 8
        cmax = 8
        while i < cmax:
            self._o_memoize('r_hex', self._r_hex)
            if self._failed:
                if i >= cmin:
                    self._o_succeed(vs, self._pos)
                return
            vs.append(self._val)
            i += 1
        self._o_succeed(vs, self._pos)

    def _s_escape_9(self):
        v = self._externs['unicode_names']
        if v is True:
            self._o_succeed(v, self._pos)
        elif v is False:
            self._o_fail()
        else:
            raise _ParsingRuntimeError('Bad predicate value')
        if self._failed:
            return
        self._o_str('N{')
        if self._failed:
            return
        self._s_escape_10()
        if self._failed:
            return
        self._o_ch('}')

    def _s_escape_10(self):
        rexp = '[A-Z][A-Z0-9]*(( [A-Z][A-Z0-9]*|(-[A-Z0-9]*)))*'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_nchar(self):
        self._o_memoize('r__filler', self._r__filler)
        self._s_nchar_1()

    def _s_nchar_1(self):
        rexp = '[0-9A-Z -]'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r_array(self):
        self._o_memoize('r_array_tag', self._r_array_tag)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch('[')
        if self._failed:
            return
        self._s_array_1()
        v__3 = self._val
        self._s_array_2()
        v__4 = self._val
        self._s_array_6()
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch(']')
        if self._failed:
            return
        self._o_succeed(
            ['array', v__1, self._fn_concat(v__3, v__4)], self._pos
        )

    def _s_array_1(self):
        self._o_memoize('r_value', self._r_value)
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _s_array_2(self):
        vs = []
        while True:
            pos = self._pos
            self._s_array_3()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_array_3(self):
        self._s_array_4()
        self._o_memoize('r_value', self._r_value)

    def _s_array_4(self):
        self._s_array_5()
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _s_array_5(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch(',')

    def _s_array_6(self):
        self._s_array_7()
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _s_array_7(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch(',')

    def _r_array_tag(self):
        self._o_memoize('r_tag', self._r_tag)
        v__1 = self._val
        self._s_array_tag_1()
        if self._failed:
            return
        self._o_succeed(v__1, self._pos)

    def _s_array_tag_1(self):
        pos = self._pos
        errpos = self._errpos
        self._s_array_tag_2()
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()

    def _s_array_tag_2(self):
        pos = self._pos
        self._o_memoize('r__whitespace', self._r__whitespace)
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r__comment', self._r__comment)

    def _r_object(self):
        self._o_memoize('r_object_tag', self._r_object_tag)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch('{')
        if self._failed:
            return
        self._s_object_1()
        v__3 = self._val
        self._s_object_2()
        v__4 = self._val
        self._s_object_6()
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch('}')
        if self._failed:
            return
        self._o_succeed(
            ['object', v__1, self._fn_concat(v__3, v__4)], self._pos
        )

    def _s_object_1(self):
        self._o_memoize('r_member', self._r_member)
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _s_object_2(self):
        vs = []
        while True:
            pos = self._pos
            self._s_object_3()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s_object_3(self):
        self._s_object_4()
        self._o_memoize('r_member', self._r_member)

    def _s_object_4(self):
        self._s_object_5()
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _s_object_5(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch(',')

    def _s_object_6(self):
        self._s_object_7()
        if self._failed:
            self._o_succeed([], self._pos)
        else:
            self._o_succeed([self._val], self._pos)

    def _s_object_7(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch(',')

    def _r_object_tag(self):
        self._o_memoize('r_tag', self._r_tag)
        v__1 = self._val
        self._s_object_tag_1()
        if self._failed:
            return
        self._o_succeed(v__1, self._pos)

    def _s_object_tag_1(self):
        pos = self._pos
        errpos = self._errpos
        self._s_object_tag_2()
        if self._failed:
            self._o_succeed(None, pos)
        else:
            self._o_rewind(pos)
            self._errpos = errpos
            self._o_fail()

    def _s_object_tag_2(self):
        pos = self._pos
        self._o_memoize('r__whitespace', self._r__whitespace)
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r__comment', self._r__comment)

    def _r_member(self):
        self._o_memoize('r_key', self._r_key)
        if self._failed:
            return
        v__1 = self._val
        if self._failed:
            return
        self._s_member_1()
        if self._failed:
            return
        self._o_memoize('r_value', self._r_value)
        if self._failed:
            return
        v__3 = self._val
        if self._failed:
            return
        self._o_succeed([v__1, v__3], self._pos)

    def _s_member_1(self):
        pos = self._pos
        self._s_member_2()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_member_3()

    def _s_member_2(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch(':')

    def _s_member_3(self):
        self._o_memoize('r__filler', self._r__filler)
        self._o_ch('=')

    def _r_key(self):
        pos = self._pos
        self._o_memoize('r_string', self._r_string)
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s_key_1()

    def _s_key_1(self):
        v = self._externs['allow_numwords']
        if v is True:
            self._o_succeed(v, self._pos)
        elif v is False:
            self._o_fail()
        else:
            raise _ParsingRuntimeError('Bad predicate value')
        if self._failed:
            return
        self._o_memoize('r__filler', self._r__filler)
        self._o_memoize('r_numword', self._r_numword)

    def _r__whitespace(self):
        vs = []
        self._s__whitespace_1()
        if self._failed:
            return
        vs.append(self._val)
        while True:
            pos = self._pos
            self._s__whitespace_1()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s__whitespace_1(self):
        rexp = '[ \n\r\t]'
        if rexp not in self._regexps:
            self._regexps[rexp] = re.compile(rexp)
        m = self._regexps[rexp].match(self._text, self._pos)
        if m:
            self._o_succeed(m.group(0), m.end())
            return
        self._o_fail()

    def _r__comment(self):
        pos = self._pos
        self._s__comment_1()
        if not self._failed:
            return
        self._o_rewind(pos)
        self._s__comment_4()

    def _s__comment_1(self):
        self._s__comment_2()
        if self._failed:
            return
        self._s__comment_3()

    def _s__comment_2(self):
        pos = self._pos
        self._o_ch('#')
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_str('//')

    def _s__comment_3(self):
        vs = []
        while True:
            pos = self._pos
            pos = self._pos
            errpos = self._errpos
            self._o_memoize('r_eol', self._r_eol)
            if self._failed:
                self._o_succeed(None, pos)
            else:
                self._o_rewind(pos)
                self._errpos = errpos
                self._o_fail()
            if not self._failed:
                self._r_any()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s__comment_4(self):
        self._o_str('/*')
        if self._failed:
            return
        while True:
            self._o_str('*/')
            if not self._failed:
                break
            self._r_any()
            if self._failed:
                break

    def _r__filler(self):
        start = self._pos
        self._s__filler_1()
        end = self._pos
        self._val = self._text[start:end]

    def _s__filler_1(self):
        vs = []
        while True:
            pos = self._pos
            self._s__filler_2()
            if self._failed or self._pos == pos:
                self._o_rewind(pos)
                break
            vs.append(self._val)
        self._o_succeed(vs, self._pos)

    def _s__filler_2(self):
        pos = self._pos
        self._o_memoize('r__whitespace', self._r__whitespace)
        if not self._failed:
            return
        self._o_rewind(pos)
        self._o_memoize('r__comment', self._r__comment)

    def _r_any(self):
        if self._pos < self._end:
            self._o_succeed(self._text[self._pos], self._pos + 1)
        else:
            self._o_fail()

    def _r_end(self):
        if self._pos == self._end:
            self._o_succeed(None, self._pos)
        else:
            self._o_fail()

    def _o_ch(self, ch):
        pos = self._pos
        if pos < self._end and self._text[pos] == ch:
            self._o_succeed(ch, self._pos + 1)
        else:
            self._o_fail()

    def _o_error(self):
        lineno, colno = self._o_offsets(self._errpos)
        if self._errpos == len(self._text):
            thing = 'end of input'
        else:
            thing = repr(self._text[self._errpos]).replace("'", '"')
        path = self._path
        return f'{path}:{lineno} Unexpected {thing} at column {colno}'

    def _o_fail(self):
        self._val = None
        self._failed = True
        self._errpos = max(self._errpos, self._pos)

    def _o_lookup(self, var):
        i = len(self._scopes) - 1
        while i >= 0:
            if var in self._scopes[i]:
                return self._scopes[i][var]
            i -= 1
        if var in self._externs:
            return self._externs[var]
        assert False, f'unknown var {var}'

    def _o_memoize(self, rule_name, fn):
        pos = self._pos
        if pos not in self._cache:
            self._cache[pos] = {}
        c = self._cache[pos]
        if rule_name in c:
            self._val, self._failed, self._pos = c[rule_name]
            return
        fn()
        c[rule_name] = (self._val, self._failed, self._pos)

    def _o_offsets(self, pos):
        lineno = 1
        colno = 1
        for i in range(pos):
            if self._text[i] == '\n':
                lineno += 1
                colno = 1
            else:
                colno += 1
        return lineno, colno

    def _o_rewind(self, newpos):
        self._o_succeed(None, newpos)

    def _o_str(self, s):
        for ch in s:
            self._o_ch(ch)
            if self._failed:
                return
        self._val = s

    def _o_succeed(self, v, newpos):
        self._val = v
        self._failed = False
        self._pos = newpos

    def _fn_colno(self):
        colno = 0
        if self._pos == self._end:
            colno += 1
        while self._pos >= colno and self._text[self._pos - colno] != '\n':
            colno += 1
        return colno

    def _fn_concat(self, xs, ys):
        return xs + ys

    def _fn_cons(self, hd, tl):
        return [hd] + tl

    def _fn_join(self, sep, strs):
        return sep.join(strs)

    def _fn_strcat(self, *args):
        return ''.join(args)
