name: Python package

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        version: "0.7.3"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up venv
      run: python run devenv

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Run tests
      run: python run tests
